name: benchmarking-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base>=4.3
  - r-tidyverse
  - r-dplyr
  - r-tidyr
  - r-stringr
  - r-ggplot2
  - r-ggpubr
  - r-patchwork
  - r-pROC
  - r-metrics
  - bioconductor-complexheatmap
  - r-circlize
  - r-devtools
  - r-knitr
  - r-rmarkdown
  - r-remotes
