name: Render R Markdown Notebooks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-notebooks
          environment-file: environment.yml
          use-mamba: true
          auto-activate-base: false
          # Enable caching!
          cache-environment: true
          cache-downloads: true

      - name: Render all Rmd notebooks
        run: |
          conda activate test-notebooks
          Rscript -e '
            files <- list.files("notebooks", pattern = "\\.Rmd$", full.names = TRUE)
            for (f in files) {
              message("Rendering ", f)
              rmarkdown::render(f, output_dir = "notebook")
            }
          '
